services:
  app:
    image: ${DOCKER_IMAGE}
    container_name: wander-jr-prod
    restart: always
    network_mode: host
    env_file:
      - .env.prod
    volumes:
      - ./data/documents:/app/data/documents
