#!/bin/bash
set -euo pipefail

ENV_FILE="${1:-.deploy/.env.prod}"
mkdir -p "$(dirname "$ENV_FILE")"

cat <<EOF > "$ENV_FILE"
# ============================================
# Wander Jr — Production Environment
# ============================================

# --- Telegram ---
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}

# --- Google Gemini (AI Studio) ---
GEMINI_API_KEY=${GEMINI_API_KEY}

# --- PostgreSQL ---
POSTGRES_USER=${POSTGRES_USER:-wander}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB:-wander_db}
POSTGRES_HOST=${POSTGRES_HOST:-localhost}
POSTGRES_PORT=${POSTGRES_PORT:-5432}
DATABASE_URL=${DATABASE_URL}

# --- Qdrant ---
QDRANT_HOST=${QDRANT_HOST:-localhost}
QDRANT_PORT=${QDRANT_PORT:-6333}
QDRANT_GRPC_PORT=${QDRANT_GRPC_PORT:-6334}
QDRANT_COLLECTION_NAME=${QDRANT_COLLECTION_NAME:-documents}
QDRANT_SPARSE_VECTOR_NAME=${QDRANT_SPARSE_VECTOR_NAME:-sparse-vector}

# --- Application ---
APP_ENV=production
APP_LOG_LEVEL=${APP_LOG_LEVEL:-INFO}
APP_HOST=${APP_HOST:-0.0.0.0}
APP_PORT=${APP_PORT:-8000}
APP_NAME=${APP_NAME:-Wander Jr}
APP_DESCRIPTION=${APP_DESCRIPTION:-Assistente inteligente institucional do CEFET-MG campus Timóteo}
APP_SERVICE_NAME=${APP_SERVICE_NAME:-wander-jr}
APP_ASSISTANT_NAME=${APP_ASSISTANT_NAME:-Wander Jr}
APP_INSTITUTION_NAME=${APP_INSTITUTION_NAME:-CEFET-MG campus Timóteo}
APP_SIGAA_URL=${APP_SIGAA_URL:-https://sig.cefetmg.br/sigaa/}
APP_SECRETARIA_PHONE=${APP_SECRETARIA_PHONE:-(31) 3845-2005}
APP_SECRETARIA_EMAIL=${APP_SECRETARIA_EMAIL:-de.te@cefetmg.br}
APP_DIRETORIA_EMAIL=${APP_DIRETORIA_EMAIL:-diretoria-te@cefetmg.br}
APP_SESSION_TIMEOUT_MINUTES=${APP_SESSION_TIMEOUT_MINUTES:-30}
APP_MAX_HISTORY_TURNS=${APP_MAX_HISTORY_TURNS:-10}

# --- RAG Settings ---
RAG_CHUNK_SIZE=${RAG_CHUNK_SIZE:-420}
RAG_CHUNK_OVERLAP=${RAG_CHUNK_OVERLAP:-24}
RAG_TOP_K=${RAG_TOP_K:-8}
RAG_SCORE_THRESHOLD=${RAG_SCORE_THRESHOLD:-0.30}
RAG_CONFIDENCE_NONE_THRESHOLD=${RAG_CONFIDENCE_NONE_THRESHOLD:-0.28}
RAG_CONFIDENCE_LOW_THRESHOLD=${RAG_CONFIDENCE_LOW_THRESHOLD:-0.48}
RAG_DOCUMENTS_PATH=${RAG_DOCUMENTS_PATH:-data/documents}
RAG_SUPPORTED_EXTENSIONS=${RAG_SUPPORTED_EXTENSIONS:-.pdf,.txt,.md}
RAG_LIST_QUERY_MIN_TOP_K=${RAG_LIST_QUERY_MIN_TOP_K:-8}
RAG_PROMPT_HISTORY_TURNS=${RAG_PROMPT_HISTORY_TURNS:-6}

# --- LLM Settings ---
LLM_MODEL=${LLM_MODEL:-gemini-2.5-flash}
LLM_FALLBACK_MODELS=${LLM_FALLBACK_MODELS:-gemini-2.5-flash-lite,gemini-3-flash}
LLM_TEMPERATURE=${LLM_TEMPERATURE:-0.3}
LLM_MAX_TOKENS=${LLM_MAX_TOKENS:-10000}
EMBEDDING_MODEL=${EMBEDDING_MODEL:-models/gemini-embedding-2-preview}
EMBEDDING_DIMENSIONS=${EMBEDDING_DIMENSIONS:-768}
EMBEDDING_REQUESTS_PER_MINUTE=${EMBEDDING_REQUESTS_PER_MINUTE:-5}
EMBEDDING_MAX_RETRIES=${EMBEDDING_MAX_RETRIES:-3}
EMBEDDING_BASE_RETRY_SECONDS=${EMBEDDING_BASE_RETRY_SECONDS:-2.0}
RAG_EMBEDDING_BATCH_SIZE=${RAG_EMBEDDING_BATCH_SIZE:-10}

# --- Document Parsing ---
LLAMA_CLOUD_API_KEY=${LLAMA_CLOUD_API_KEY:-}
LLAMA_PARSE_TIER=${LLAMA_PARSE_TIER:-cost_effective}

# --- Reranker ---
RERANKER_ENABLED=${RERANKER_ENABLED:-true}
RERANKER_MODEL=${RERANKER_MODEL:-ms-marco-MultiBERT-L-12}
RERANKER_TOP_K=${RERANKER_TOP_K:-5}
RERANKER_RETRIEVAL_MULTIPLIER=${RERANKER_RETRIEVAL_MULTIPLIER:-3}

# --- Docker / Compose ---
APP_CONTAINER_NAME=${APP_CONTAINER_NAME:-wander-jr-prod}
APP_BIND_PORT=${APP_BIND_PORT:-8000}
APP_DOCUMENTS_MOUNT_PATH=${APP_DOCUMENTS_MOUNT_PATH:-/app/data/documents}
POSTGRES_IMAGE=${POSTGRES_IMAGE:-postgres:16-alpine}
POSTGRES_CONTAINER_NAME=${POSTGRES_CONTAINER_NAME:-wander-postgres}
POSTGRES_BIND_PORT=${POSTGRES_BIND_PORT:-5436}
QDRANT_IMAGE=${QDRANT_IMAGE:-qdrant/qdrant:latest}
QDRANT_CONTAINER_NAME=${QDRANT_CONTAINER_NAME:-wander-qdrant}
QDRANT_CONTAINER_NAME_PROD=${QDRANT_CONTAINER_NAME_PROD:-wander-qdrant-prod}
HOST_DOCUMENTS_PATH=${HOST_DOCUMENTS_PATH:-./data/documents}
QDRANT_STORAGE_PATH=${QDRANT_STORAGE_PATH:-./data/qdrant_storage}
QDRANT_SNAPSHOTS_PATH=${QDRANT_SNAPSHOTS_PATH:-./data/qdrant_snapshots}

# --- Deploy ---
DOCKER_IMAGE=${DOCKER_IMAGE:-}
EOF
